### ISSUE TITLE
Showing % of checkpoint completion

### ISSUE THREAD

**Issue by tparveen** [rich-at-thinkful/auditor-issues#3]
- [ ] Bug
- [X ] Feature request
- [ ] Other

Enter details here
After each of the checkpoints, can we put a % of the completion - for example, 

Client-side   programming with React | completion Rate in %
--
14/21                                                         |  67
15/21                                                         | 71

Web apps mock   interview | completion Rate in %
--
✓                                             |  100
✓                                             | 100

Is there a way to prioritize this to be done by January 10th, 2021?

**Comment by rich-at-thinkful** [comment]
@tparveen Can do that. Would make each grid cell double wide in an already very large grid - is there a reason it needs all the info at same time or should it be a toggle button for something like "Total or Percentage".  I believe a lot of instructors tend to download the grid in CSV and reformat.

**Comment by rich-at-thinkful** [comment]
Added toggle button to change view between percentage complete and actual
Pushed to master
