### ISSUE TITLE
Put your bug or request title here

### ISSUE THREAD

**Issue by kcohane00** [rich-at-thinkful/auditor-issues#4]
- [ x] Bug

Enter details here
Hi Rich for DMI Cohort 5 11.30 start date, Rronniba Pemberton is coming up as 80% complete for Campaigns in the auditor, but I went to her dashboard and she finished the module.

**Comment by rich-at-thinkful** [comment]
Resolved offline. Student Dashboard uses different metric to show module complete vs Student Auditor which just adds up all complete checkpoints.
